//! School-manager user provisioning with typed relationship inputs.
//!
//! This is the canonical production provisioning boundary. The browser never
//! supplies credentials. All caller-controlled relationships are validated
//! before the external Auth write, all local rows are committed atomically,
//! and a failed local transaction compensates the newly-created Auth account.

use dioxus::prelude::*;
use serde::{Deserialize, Serialize};

#[cfg(feature = "server")]
use {
    crate::app_state::extract_server_state,
    crate::domain::UserId,
    crate::services::supabase_auth::SupabaseAdminService,
    sqlx::Row,
    uuid::Uuid,
};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ProvisionSchoolUserRequest {
    pub name: String,
    pub email: String,
    pub role: String,
    pub metadata: Option<serde_json::Value>,
    pub talent_profile_ref: Option<String>,
    pub teacher_class_ids: Vec<String>,
    pub teacher_subject_ids: Vec<String>,
    pub student_class_id: Option<String>,
    pub student_parent_user_id: Option<String>,
    pub parent_student_user_ids: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ProvisionSchoolUserResponse {
    pub user_id: String,
    /// One-time credential generated by the server. It is returned only from
    /// the successful provisioning response and must never be logged.
    pub temporary_password: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ProvisionableRole {
    Teacher,
    Student,
    Parent,
}

impl ProvisionableRole {
    fn parse(value: &str) -> Option<Self> {
        match value {
            "Teacher" => Some(Self::Teacher),
            "Student" => Some(Self::Student),
            "Parent" => Some(Self::Parent),
            _ => None,
        }
    }

    fn as_str(self) -> &'static str {
        match self {
            Self::Teacher => "Teacher",
            Self::Student => "Student",
            Self::Parent => "Parent",
        }
    }
}

#[server(endpoint = "user_management/provision")]
pub async fn provision_school_user(
    request: ProvisionSchoolUserRequest,
) -> Result<ProvisionSchoolUserResponse, ServerFnError> {
    #[cfg(feature = "server")]
    {
        let (actor, pool) = crate::server_functions::rls_helpers::extract_user_with_full_rls().await?;
        if actor.role != "SchoolManager" {
            return Err(ServerFnError::new("user.forbidden"));
        }

        let name = request.name.trim().to_string();
        let email = request.email.trim().to_ascii_lowercase();
        let role = ProvisionableRole::parse(request.role.trim())
            .ok_or_else(|| ServerFnError::new("user.role_not_provisionable"))?;

        if name.is_empty() {
            return Err(ServerFnError::new("user.name_required"));
        }
        if crate::utils::validation::validate_email(&email).is_err() {
            return Err(ServerFnError::new("user.email_invalid"));
        }
        if let Some(metadata) = request.metadata.as_ref() {
            if !metadata.is_object() {
                return Err(ServerFnError::new("user.metadata_invalid"));
            }
        }

        let actor_id = Uuid::parse_str(&actor.id)
            .map_err(|_| ServerFnError::new("user.invalid_session"))?;
        let school_id = sqlx::query_scalar::<_, Uuid>(
            "SELECT school_id FROM users WHERE id = $1 AND is_active = TRUE",
        )
        .bind(actor_id)
        .fetch_optional(&*pool)
        .await
        .map_err(|error| {
            tracing::error!(%error, actor_id = %actor_id, "provisioning school lookup failed");
            ServerFnError::new("user.school_unavailable")
        })?
        .ok_or_else(|| ServerFnError::new("user.school_unavailable"))?;

        let local_duplicate = sqlx::query_scalar::<_, bool>(
            "SELECT EXISTS (SELECT 1 FROM users WHERE lower(email) = lower($1))",
        )
        .bind(&email)
        .fetch_one(&*pool)
        .await
        .map_err(|error| {
            tracing::error!(%error, "provisioning duplicate-email check failed");
            ServerFnError::new("user.provisioning_unavailable")
        })?;
        if local_duplicate {
            return Err(ServerFnError::new("user.duplicate_email"));
        }

        let role_id = sqlx::query_scalar::<_, Uuid>(
            "SELECT id FROM roles WHERE name::text = $1",
        )
        .bind(role.as_str())
        .fetch_optional(&*pool)
        .await
        .map_err(|error| {
            tracing::error!(%error, role = role.as_str(), "provisioning role lookup failed");
            ServerFnError::new("user.role_unavailable")
        })?
        .ok_or_else(|| ServerFnError::new("user.role_unavailable"))?;

        let teacher_class_ids = parse_uuid_list(&request.teacher_class_ids, "user.class_id_invalid")?;
        let teacher_subject_ids = parse_uuid_list(&request.teacher_subject_ids, "user.subject_id_invalid")?;
        let parent_student_user_ids =
            parse_uuid_list(&request.parent_student_user_ids, "user.student_id_invalid")?;
        let student_class_id = parse_optional_uuid(
            request.student_class_id.as_deref(),
            "user.class_id_invalid",
        )?;
        let student_parent_user_id = parse_optional_uuid(
            request.student_parent_user_id.as_deref(),
            "user.parent_id_invalid",
        )?;

        validate_role_relationship_shape(
            role,
            &teacher_class_ids,
            &teacher_subject_ids,
            student_class_id,
            student_parent_user_id,
            &parent_student_user_ids,
        )?;

        let mut teacher_subject_names = Vec::<String>::new();
        match role {
            ProvisionableRole::Teacher => {
                if !teacher_class_ids.is_empty() {
                    let count = sqlx::query_scalar::<_, i64>(
                        "SELECT COUNT(*) FROM class_sections WHERE school_id = $1 AND id = ANY($2::uuid[])",
                    )
                    .bind(school_id)
                    .bind(&teacher_class_ids)
                    .fetch_one(&*pool)
                    .await
                    .map_err(|error| {
                        tracing::error!(%error, "teacher class validation failed");
                        ServerFnError::new("user.relationship_validation_failed")
                    })?;
                    if count != teacher_class_ids.len() as i64 {
                        return Err(ServerFnError::new("user.class_outside_school"));
                    }
                }

                if !teacher_subject_ids.is_empty() {
                    let rows = sqlx::query(
                        "SELECT id, name FROM subjects WHERE id = ANY($1::uuid[]) ORDER BY name",
                    )
                    .bind(&teacher_subject_ids)
                    .fetch_all(&*pool)
                    .await
                    .map_err(|error| {
                        tracing::error!(%error, "teacher subject validation failed");
                        ServerFnError::new("user.relationship_validation_failed")
                    })?;
                    if rows.len() != teacher_subject_ids.len() {
                        return Err(ServerFnError::new("user.subject_invalid"));
                    }
                    teacher_subject_names = rows
                        .into_iter()
                        .map(|row| row.get::<String, _>("name"))
                        .collect();
                }
            }
            ProvisionableRole::Student => {
                if let Some(class_id) = student_class_id {
                    let valid = sqlx::query_scalar::<_, bool>(
                        "SELECT EXISTS (SELECT 1 FROM class_sections WHERE id = $1 AND school_id = $2)",
                    )
                    .bind(class_id)
                    .bind(school_id)
                    .fetch_one(&*pool)
                    .await
                    .map_err(|error| {
                        tracing::error!(%error, "student class validation failed");
                        ServerFnError::new("user.relationship_validation_failed")
                    })?;
                    if !valid {
                        return Err(ServerFnError::new("user.class_outside_school"));
                    }
                }

                if let Some(parent_id) = student_parent_user_id {
                    let valid = sqlx::query_scalar::<_, bool>(
                        r#"
                        SELECT EXISTS (
                            SELECT 1
                            FROM users u
                            JOIN roles r ON r.id = u.role_id
                            JOIN parents p ON p.user_id = u.id AND p.school_id = u.school_id
                            WHERE u.id = $1
                              AND u.school_id = $2
                              AND u.is_active = TRUE
                              AND r.name::text = 'Parent'
                        )
                        "#,
                    )
                    .bind(parent_id)
                    .bind(school_id)
                    .fetch_one(&*pool)
                    .await
                    .map_err(|error| {
                        tracing::error!(%error, "student parent validation failed");
                        ServerFnError::new("user.relationship_validation_failed")
                    })?;
                    if !valid {
                        return Err(ServerFnError::new("user.parent_outside_school"));
                    }
                }
            }
            ProvisionableRole::Parent => {
                if !parent_student_user_ids.is_empty() {
                    let count = sqlx::query_scalar::<_, i64>(
                        r#"
                        SELECT COUNT(*)
                        FROM students s
                        JOIN users u ON u.id = s.user_id
                        WHERE u.id = ANY($1::uuid[])
                          AND s.school_id = $2
                          AND u.school_id = $2
                          AND u.is_active = TRUE
                          AND s.parent_id IS NULL
                        "#,
                    )
                    .bind(&parent_student_user_ids)
                    .bind(school_id)
                    .fetch_one(&*pool)
                    .await
                    .map_err(|error| {
                        tracing::error!(%error, "parent student validation failed");
                        ServerFnError::new("user.relationship_validation_failed")
                    })?;
                    if count != parent_student_user_ids.len() as i64 {
                        return Err(ServerFnError::new("user.student_relationship_conflict"));
                    }
                }
            }
        }

        let state = extract_server_state()?;
        let supabase_service = SupabaseAdminService::new(state.supabase_config.clone());
        let temporary_password = generate_temporary_password();
        let auth_metadata = serde_json::json!({
            "name": name,
            "role": role.as_str(),
            "school_id": school_id.to_string()
        });
        let auth_user = supabase_service
            .create_user(&email, &temporary_password, auth_metadata)
            .await
            .map_err(|error| {
                tracing::warn!(%error, "Supabase Auth provisioning failed");
                ServerFnError::new("user.auth_creation_failed")
            })?;
        let new_user_uuid = Uuid::parse_str(&auth_user.id).map_err(|error| {
            tracing::error!(%error, "Supabase Auth returned invalid user id");
            ServerFnError::new("user.auth_creation_failed")
        })?;

        let local_result: Result<(), sqlx::Error> = async {
            let mut tx = pool.begin().await?;

            sqlx::query(
                r#"
                INSERT INTO users (id, name, email, role_id, school_id, is_active, metadata)
                VALUES ($1, $2, $3, $4, $5, TRUE, $6)
                "#,
            )
            .bind(new_user_uuid)
            .bind(&name)
            .bind(&email)
            .bind(role_id)
            .bind(school_id)
            .bind(request.metadata.clone())
            .execute(&mut *tx)
            .await?;

            match role {
                ProvisionableRole::Teacher => {
                    let teacher_id = Uuid::new_v4();
                    let subject_text = if teacher_subject_names.is_empty() {
                        None
                    } else {
                        Some(teacher_subject_names.join(", "))
                    };
                    sqlx::query(
                        "INSERT INTO teachers (id, user_id, school_id, subject, created_at) VALUES ($1, $2, $3, $4, NOW())",
                    )
                    .bind(teacher_id)
                    .bind(new_user_uuid)
                    .bind(school_id)
                    .bind(subject_text)
                    .execute(&mut *tx)
                    .await?;

                    if !teacher_class_ids.is_empty() {
                        sqlx::query(
                            r#"
                            INSERT INTO teaching_assignments (id, teacher_id, class_section_id)
                            SELECT gen_random_uuid(), $1, unnest($2::uuid[])
                            "#,
                        )
                        .bind(teacher_id)
                        .bind(&teacher_class_ids)
                        .execute(&mut *tx)
                        .await?;
                    }
                }
                ProvisionableRole::Student => {
                    let student_id = Uuid::new_v4();
                    sqlx::query(
                        r#"
                        INSERT INTO students (id, user_id, school_id, parent_id, talent_profile_ref, created_at)
                        VALUES ($1, $2, $3, $4, $5, NOW())
                        "#,
                    )
                    .bind(student_id)
                    .bind(new_user_uuid)
                    .bind(school_id)
                    .bind(student_parent_user_id)
                    .bind(request.talent_profile_ref.clone())
                    .execute(&mut *tx)
                    .await?;

                    if let Some(class_id) = student_class_id {
                        sqlx::query(
                            "INSERT INTO enrollments (class_section_id, student_id, enrolled_at) VALUES ($1, $2, NOW())",
                        )
                        .bind(class_id)
                        .bind(student_id)
                        .execute(&mut *tx)
                        .await?;
                    }
                }
                ProvisionableRole::Parent => {
                    sqlx::query(
                        "INSERT INTO parents (id, user_id, school_id) VALUES ($1, $2, $3)",
                    )
                    .bind(Uuid::new_v4())
                    .bind(new_user_uuid)
                    .bind(school_id)
                    .execute(&mut *tx)
                    .await?;

                    if !parent_student_user_ids.is_empty() {
                        let result = sqlx::query(
                            r#"
                            UPDATE students
                            SET parent_id = $1
                            WHERE user_id = ANY($2::uuid[])
                              AND school_id = $3
                              AND parent_id IS NULL
                            "#,
                        )
                        .bind(new_user_uuid)
                        .bind(&parent_student_user_ids)
                        .bind(school_id)
                        .execute(&mut *tx)
                        .await?;
                        if result.rows_affected() != parent_student_user_ids.len() as u64 {
                            return Err(sqlx::Error::Protocol(
                                "parent relationship changed during provisioning".into(),
                            ));
                        }
                    }
                }
            }

            tx.commit().await?;
            Ok(())
        }
        .await;

        if let Err(error) = local_result {
            tracing::error!(%error, user_id = %new_user_uuid, "local provisioning transaction failed");
            let new_user_id = UserId::from(new_user_uuid);
            if let Err(cleanup_error) = supabase_service.delete_user(&new_user_id).await {
                tracing::error!(%cleanup_error, user_id = %new_user_uuid, "provisioning Auth compensation failed");
                return Err(ServerFnError::new(
                    "user.provisioning_reconciliation_required",
                ));
            }
            return Err(ServerFnError::new("user.provisioning_failed"));
        }

        Ok(ProvisionSchoolUserResponse {
            user_id: new_user_uuid.to_string(),
            temporary_password,
        })
    }

    #[cfg(not(feature = "server"))]
    Err(ServerFnError::new("server only"))
}

#[cfg(feature = "server")]
fn parse_uuid_list(values: &[String], code: &'static str) -> Result<Vec<Uuid>, ServerFnError> {
    let mut parsed = values
        .iter()
        .map(|value| Uuid::parse_str(value).map_err(|_| ServerFnError::new(code)))
        .collect::<Result<Vec<_>, _>>()?;
    parsed.sort_unstable();
    parsed.dedup();
    Ok(parsed)
}

#[cfg(feature = "server")]
fn parse_optional_uuid(
    value: Option<&str>,
    code: &'static str,
) -> Result<Option<Uuid>, ServerFnError> {
    value
        .filter(|value| !value.trim().is_empty())
        .map(|value| Uuid::parse_str(value).map_err(|_| ServerFnError::new(code)))
        .transpose()
}

#[cfg(feature = "server")]
fn validate_role_relationship_shape(
    role: ProvisionableRole,
    teacher_class_ids: &[Uuid],
    teacher_subject_ids: &[Uuid],
    student_class_id: Option<Uuid>,
    student_parent_user_id: Option<Uuid>,
    parent_student_user_ids: &[Uuid],
) -> Result<(), ServerFnError> {
    let invalid = match role {
        ProvisionableRole::Teacher => {
            student_class_id.is_some()
                || student_parent_user_id.is_some()
                || !parent_student_user_ids.is_empty()
        }
        ProvisionableRole::Student => {
            !teacher_class_ids.is_empty()
                || !teacher_subject_ids.is_empty()
                || !parent_student_user_ids.is_empty()
        }
        ProvisionableRole::Parent => {
            !teacher_class_ids.is_empty()
                || !teacher_subject_ids.is_empty()
                || student_class_id.is_some()
                || student_parent_user_id.is_some()
        }
    };
    if invalid {
        Err(ServerFnError::new("user.relationship_shape_invalid"))
    } else {
        Ok(())
    }
}

#[cfg(feature = "server")]
fn generate_temporary_password() -> String {
    // UUID v4 contributes ~122 random bits. Prefix/suffix make the generated
    // credential satisfy common upper/lower/digit/symbol password policies.
    format!("Et!{}9a", Uuid::new_v4().simple())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn provisioning_role_allowlist_excludes_privileged_roles() {
        assert_eq!(ProvisionableRole::parse("Teacher"), Some(ProvisionableRole::Teacher));
        assert_eq!(ProvisionableRole::parse("Student"), Some(ProvisionableRole::Student));
        assert_eq!(ProvisionableRole::parse("Parent"), Some(ProvisionableRole::Parent));
        for value in ["SchoolManager", "PlatformAdmin", "admin", "system_job", ""] {
            assert_eq!(ProvisionableRole::parse(value), None);
        }
    }

    #[cfg(feature = "server")]
    #[test]
    fn temporary_password_is_server_generated_and_high_entropy_length() {
        let first = generate_temporary_password();
        let second = generate_temporary_password();
        assert_ne!(first, second);
        assert!(first.len() >= 36);
        assert!(first.starts_with("Et!"));
    }
}
