pub mod assignment_personalization_job_repository;
#[cfg(test)]
mod assignment_personalization_job_repository_tests;
pub mod assignment_repository;
pub mod audit_log_repository;
pub mod authorized_assignment_repository;
#[cfg(test)]
mod authorized_assignment_repository_tests;
pub mod base;
pub mod class_section_repository;
pub mod custom_assignment_repository;
pub mod enrollment_repository;
pub mod invite_repository;
pub mod knowledge_asset_repository;
#[cfg(test)]
mod knowledge_asset_repository_tests;
pub mod knowledge_audit_repository;
pub mod knowledge_ingestion_job_repository;
pub mod lecture_repository;
pub mod material_repository;
pub mod mock_impl;
pub mod notification_repository;
pub mod parent_repository;
pub mod profile_change_request_repository;
pub mod profile_repository;
pub mod report_repository;
pub mod role_repository;
pub mod school_repository;
pub mod student_repository;
pub mod subject_repository;
pub mod submission_repository;
pub mod teacher_repository;
pub mod teaching_assignment_repository;
pub mod traits;
pub mod user_preferences_repository;
pub mod user_repository;

// Re-export all repositories
pub use assignment_personalization_job_repository::*;
pub use assignment_repository::*;
pub use audit_log_repository::*;
pub use authorized_assignment_repository::*;
pub use base::*;
pub use class_section_repository::*;
pub use custom_assignment_repository::*;
pub use enrollment_repository::*;
pub use invite_repository::*;
pub use knowledge_asset_repository::*;
pub use knowledge_audit_repository::*;
pub use knowledge_ingestion_job_repository::*;
pub use lecture_repository::*;
pub use material_repository::*;
pub use mock_impl::*;
pub use notification_repository::*;
pub use parent_repository::*;
pub use profile_change_request_repository::*;
pub use profile_repository::*;
pub use report_repository::*;
pub use role_repository::*;
pub use school_repository::*;
pub use student_repository::*;
pub use subject_repository::*;
pub use submission_repository::*;
pub use teacher_repository::*;
pub use teaching_assignment_repository::*;
pub use traits::*;
pub use user_preferences_repository::*;
pub use user_repository::*;
