name: Fix signature inventory

on:
  pull_request:
    types:
      - synchronize
    paths:
      - .github/workflows/fix-signature-inventory.yml

permissions:
  contents: write

jobs:
  patch:
    runs-on: ubuntu-24.04
    steps:
      - run: echo staging
